/*
 * generated by Xtext
 */
package org.yakindu.sct.model.stext.ui.contentassist

import org.yakindu.sct.model.stext.ui.contentassist.AbstractSTextProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class STextProposalProvider extends AbstractSTextProposalProvider {
}
